package SqlQuery.Update;

import Database.UpdatesConnection;
import java.io.FileNotFoundException;
/**
 * This class builds update Publisher query from data
 * generated by update book interface.
 * @author russellfincham
 * @version 0.1
 * @since 16-07-18
 */
public class UpdatePublisher {
    /**
     * This method generates SQL For a publisher update.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to UpdatePublisherController.btnPublisherUpdAction method for
     * the Update publisher Interface.
     * Data validity checking handled before execution of UPDATE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @param recordToUpdate The ID of the record to update
     * @param pubId New Publisher ID
     * @param pubName New Publisher name
     * @param pubPostcode New postcode
     * @param pubAddress1 New address line 1
     * @param pubAddress2 New address line 2
     * @param pubAddress3 New address line 3
     * @param pubTown New Town address
     * @param pubCounty New county address
     * @return String result of SQL transaction.
     */
    public static String Query(String recordToUpdate, String pubId, String pubName,
                               String pubPostcode, String pubAddress1,
                               String pubAddress2, String pubAddress3,
                               String pubTown, String pubCounty)
            throws FileNotFoundException {

        String result;

        String sqlQuery = "UPDATE publishers SET "
                + "publisher_id = '" + pubId + "', "
                + "publisher_name = '" + pubName + "', "
                + "address_1 = '" + pubAddress1 + "', "
                + "address_2 = '" + pubAddress2 + "', "
                + "address_3 = '" + pubAddress3 + "', "
                + "address_town = '" + pubTown + "', "
                + "address_postcode = '" + pubPostcode + "', "
                + "address_county = '" + pubCounty + "' "
                + "WHERE publisher_id = '" + recordToUpdate + "';";

        result = UpdatesConnection.queryDatabase(sqlQuery);

        return result;
    }
}