package SqlQuery;

import Database.DbConnection;
import Database.UpdateQuery;
import java.io.FileNotFoundException;
import java.util.ArrayList;

/**
 * This class builds add Author query from data
 * generated by add Author interface.
 * @author russellfincham
 * @version 0.1
 * @since 12-07-18
 */

public class AddAuthor {
    /**
     * This method generates SQL For a Author addition.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to AddAuthorController.btnAuthorAddAction method for
     * the add genre Interface.
     * Data validity checking handled before execution of INSERT.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param genreId
     * @Param genreName
     * @return String result of SQL transaction.
     */
    public static String Query(String authorId, String authorFirstName,
                               String authorSurname)
            throws FileNotFoundException {

        String result;

        String sqlTestID = "SELECT 1 FROM authors WHERE author_id = '"
                + authorId + "' LIMIT 1;";

        String sqlTestFName = "SELECT 1 FROM authors WHERE author_firstname = '"
                + authorFirstName + "' LIMIT 1;";

        String sqlTestSName = "SELECT 1 FROM authors WHERE author_surname = '"
                + authorSurname + "' LIMIT 1;";

        String sqlQuery = "INSERT INTO authors (author_id, author_firstname, author_surname) "
                + "VALUES ('" + authorId + "', '" + authorFirstName + "', '" + authorSurname + "');";

        ArrayList<String[]> idTest = new ArrayList<>(DbConnection.Manager(sqlTestID));
        ArrayList<String[]> fNameTest = new ArrayList<>(DbConnection.Manager(sqlTestFName));
        ArrayList<String[]> sNameTest = new ArrayList<>(DbConnection.Manager(sqlTestSName));

        if (idTest.get(0)[0].equals("1")) {
            result = "Author ID already in use.";
        }
        else if ((fNameTest.get(0)[0].equals("1")) && (fNameTest.get(0)[0].equals("1"))) {
            result = " Name already in system.";
        }
        else {
            result = UpdateQuery.queryDatabase(sqlQuery);
        }

        return result;
    }
}