package SqlQuery;

import Database.DbConnection;
import Database.UpdateQuery;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;

/**
 * This class builds add genre query from data
 * generated by add genre interface.
 * @author russellfincham
 * @version 0.1
 * @since 12-07-18
 */

public class AddGenre {
    /**
     * This method generates SQL For a genre addition.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to AddGenreController.btnGernreAddAction method for
     * the add genre Interface.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param genreId
     * @Param genreName
     * @return String result of SQL transaction.
     */
    public static String Query(String genreId, String genreName)
                                    throws FileNotFoundException {


        String sqlQuery = "INSERT INTO genre (genre_name, genre_id) "
                + "VALUES ('" + genreName + "', '" + genreId + "');";

        String result = UpdateQuery.queryDatabase(sqlQuery);

        return result;
    }
}