package SqlQuery;

import Database.DbConnection;

import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * This class manages search data generated by Author searches.
 * It
 * @author russellfincham
 * @version 0.2
 * @since 05-07-18
 */

public class AuthorSearch {
    /**
     * This method generates SQL FOR a search of the Authors table.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to btnSearchBookAction method for the Home user Interface.
     * @throws FileNotFoundException if data file cannot be accessed by
     * DbCredentials.DbUser.
     * @param authorId
     * @param authorFName
     * @param authorLName
     * @return List Array of results returned to search book button action control.
     */
    public static List<String[]> Query(String authorId, String authorFName, String authorLName)
            throws FileNotFoundException {

        String sqlQuery = "SELECT * FROM authors WHERE author_id LIKE '%" + authorId + "%' "
                + "AND author_firstname LIKE '%" + authorFName + "%' "
                + "AND author_lastname LIKE '%" + authorLName + "%';";

        ArrayList<String[]> searchResult = new ArrayList<>(DbConnection.Manager(sqlQuery));

        return searchResult;
    }
}
