package SqlQuery;

import Database.DbConnection;
import Database.UpdatesConnection;
import java.io.FileNotFoundException;
import java.util.ArrayList;

/**
 * This class builds delete Publisher query from data
 * generated by delete Publisher interface.
 * @author russellfincham
 * @version 0.1
 * @since 16-07-18
 */

public class DeletePublisher {
    /**
     * This method generates SQL For a Publisher deletion.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to DeletePublisherController.btnPubDelAction method for
     * the Delete Publisher Interface.
     * Data validity checking handled before execution of DELETE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param publisherId
     * @return String result of SQL transaction.
     */
    public static String Query(String publisherId)
            throws FileNotFoundException {

        String sqlTest = "SELECT 1 FROM books WHERE publisher_id = '"
                + publisherId + "' LIMIT 1;";

        String sqlQuery = "DELETE FROM publishers WHERE "
                + "publisher_id = '" + publisherId + "';";

        ArrayList<String[]> Test = new ArrayList<>(DbConnection.Manager(sqlTest));

        if (Test.get(0)[0].equals("1")) {
            return "Cannot Delete.  Assigned to books";
        }
        else {
            return UpdatesConnection.queryDatabase(sqlQuery);
        }
    }
}