package SqlQuery;

import Database.DbConnection;
import Database.UpdateQuery;
import java.io.FileNotFoundException;
import java.util.ArrayList;

/**
 * This class builds delete Genre query from data
 * generated by delete Genre interface.
 * @author russellfincham
 * @version 0.1
 * @since 16-07-18
 */

public class DeleteGenre {
    /**
     * This method generates SQL For a Genre deletion.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to DeleteGenreController.btnGenreDelAction method for
     * the Delete Genre Interface.
     * Data validity checking handled before execution of DELETE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param genreId
     * @return String result of SQL transaction.
     */
    public static String Query(String genreId)
            throws FileNotFoundException {

        String sqlTest = "SELECT 1 FROM books WHERE genre_id = '"
                + genreId + "' LIMIT 1;";

        String sqlQuery = "DELETE FROM genre WHERE "
                + "genre_id = '" + genreId + "';";

        ArrayList<String[]> Test = new ArrayList<>(DbConnection.Manager(sqlTest));

        if (Test.get(0)[0].equals("1")) {
            return "Cannot Delete.  Assigned to books";
        }
        else {
            return UpdateQuery.queryDatabase(sqlQuery);
        }
    }
}