package SqlQuery;

import Database.UpdateQuery;
import java.io.FileNotFoundException;

/**
 * This class builds delete book query from data
 * generated by delete book interface.
 * @author russellfincham
 * @version 0.1
 * @since 16-07-18
 */

public class DeleteBook {
    /**
     * This method generates SQL For a book deletion.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to DeleteBookController.btnBookDelAction method for
     * the Delete Book Interface.
     * Data validity checking handled before execution of DELETE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param bookId
     * @return String result of SQL transaction.
     */
    public static String Query(String bookId)
            throws FileNotFoundException {

        String result;

        String sqlQuery = "DELETE FROM books WHERE "
                + "id = '" + bookId + "';";

        result = UpdateQuery.queryDatabase(sqlQuery);

        return result;
    }
}