package SqlQuery;

import Database.DbConnection;
import Database.UpdateQuery;
import java.io.FileNotFoundException;
import java.util.ArrayList;

/**
 * This class builds delete Author query from data
 * generated by delete Author interface.
 * @author russellfincham
 * @version 0.1
 * @since 16-07-18
 */

public class DeleteAuthor {
    /**
     * This method generates SQL For an Author deletion.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to DeleteAuthorController.btnAuthorDelAction method for
     * the Delete Author Interface.
     * Data validity checking handled before execution of DELETE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param AuthorId
     * @return String result of SQL transaction.
     */
    public static String Query(String authorId)
            throws FileNotFoundException {

        String sqlTest = "SELECT 1 FROM books WHERE author_id = '"
                + authorId + "' LIMIT 1;";

        String sqlQuery = "DELETE FROM authors WHERE "
                + "author_id = '" + authorId + "';";

        ArrayList<String[]> Test = new ArrayList<>(DbConnection.Manager(sqlTest));

        if (Test.get(0)[0].equals("1")) {
            return "Cannot Delete.  Assigned to books";
        }
        else {
            return UpdateQuery.queryDatabase(sqlQuery);
        }
    }
}