package SqlQuery;

import Database.UpdatesConnection;
import java.io.FileNotFoundException;

/**
 * This class builds update Author query from data
 * generated by update Author interface.
 * @author russellfincham
 * @version 0.2
 * @since 17-07-18
 */

public class UpdateAuthor {
    /**
     * This method generates SQL For an Author Update.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to UpdateAuthorController.btnAuthorUpdAction method for
     * the UpdateAuthor Interface.
     * Data validity checking handled before execution of UPDATE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param recordToUpdate
     * @Param authorId
     * @Param authorFName
     * @Param authorSName
     * @return String result of SQL transaction.
     */
    public static String Query(String recordToUpdate, String authorId, String authorFName,
                               String authorSName)
            throws FileNotFoundException {

        String result;

        String sqlQuery = "UPDATE authors SET "
                + "author_id = '" + authorId + "', "
                + "author_firstname = '" + authorFName + "', "
                + "author_surname = '" + authorSName + "' "
                + "WHERE author_id = '" + recordToUpdate + "';";

        result = UpdatesConnection.queryDatabase(sqlQuery);

        return result;
    }
}