package SqlQuery;

import Database.UpdateQuery;
import java.io.FileNotFoundException;

/**
 * This class builds update book query from data
 * generated by update book interface.
 * @author russellfincham
 * @version 0.1
 * @since 14-07-18
 */

public class UpdateBook {
    /**
     * This method generates SQL For a book update.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to UpdateBookController.btnBookUpdAction method for
     * the Update Book Interface.
     * Data validity checking handled before execution of UPDATE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param recordToUpdate
     * @Param bookId
     * @Param bookTitle
     * @Param bookDescription
     * @Param bookPubDate
     * @Param bookEdition
     * @Param bookPrice
     * @Param bookPublisherId
     * @Param bookAuthorId
     * @Param bookGenreId
     * @Param bookQty
     * @return String result of SQL transaction.
     */
    public static String Query(String recordToUpdate, String bookId, String bookTitle,
                               String bookDescription, String bookPubDate,
                               String bookEdition, String bookPrice,
                               String bookPublisherId, String bookAuthorId,
                               String bookGenreId, String bookQty)
            throws FileNotFoundException {

        String result;

        String sqlQuery = "UPDATE books SET "
                + "id = '" + bookId + "', "
                + "title = '" + bookTitle + "', "
                + "description = '" + bookDescription + "', "
                + "genre_id = '" + bookGenreId + "', "
                + "price = '" + bookPrice + "', "
                + "author_id = '" + bookAuthorId + "', "
                + "publisher_id = '" + bookPublisherId + "', "
                + "publish_date = '" + bookPubDate + "', "
                + "edition = '" + bookEdition + "', "
                + "qty = '" + bookQty + "' "
                + "WHERE id = '" + recordToUpdate + "';";

        System.out.println(sqlQuery);

        result = UpdateQuery.queryDatabase(sqlQuery);

        return result;
    }
}