package SqlQuery;

import Database.UpdatesConnection;
import java.io.FileNotFoundException;

/**
 * This class builds update Genre query from data
 * generated by update Genre interface.
 * @author russellfincham
 * @version 0.2
 * @since 17-07-18
 */

public class UpdateGenre {
    /**
     * This method generates SQL For a Genre Update.
     * It generates the query which it then passes to the
     * database connection manager DbConnection.Manager. Results then
     * returned to UpdateGenreController.btnGenreUpdAction method for
     * the UpdateGenre Interface.
     * Data validity checking handled before execution of UPDATE.
     * @throws FileNotFoundException if data file cannot be accessed by
     * @Param recordToUpdate
     * @Param genreId
     * @Param genreName
     * @return String result of SQL transaction.
     */
    public static String Query(String recordToUpdate, String genreId, String genreName)
            throws FileNotFoundException {

        String result;

        String sqlQuery = "UPDATE genre SET "
                + "genre_id = '" + genreId + "', "
                + "genre_name = '" + genreName + "' "
                + "WHERE genre_id = '" + recordToUpdate + "';";

        result = UpdatesConnection.queryDatabase(sqlQuery);

        return result;
    }
}